using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WL.UserInterface.Systems.Languages.Windows;

[GenerateTypedNameReferences]
public sealed partial class LanguagesWindow : DefaultWindow
{
    public LanguagesWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
