using Content.Client._WL.UserInterface.Systems.Languages;
using Content.Shared._WL.Languages;
using Content.Client._WL.Languages;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client._WL.UserInterface.Systems.Languages.LanguageUI;

[GenerateTypedNameReferences]
public sealed partial class LanguageItemControl : BoxContainer
{
    public LanguageItemControl()
    {
        RobustXamlLoader.Load(this);
        ChooseButton.OnPressed += _ => OnChoosePressed?.Invoke(_languageId);
    }

    private ProtoId<LanguagePrototype> _languageId;
    public event Action<ProtoId<LanguagePrototype>>? OnChoosePressed;

    public void SetLanguage(ProtoId<LanguagePrototype> protoId)
    {
        _languageId = protoId;
    }
}
