using System.Numerics;
using Content.Shared.Paper;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Paper.UI;

[GenerateTypedNameReferences]
public sealed partial class StampWidget : PanelContainer
{
    private static readonly ProtoId<ShaderPrototype> PaperStamp = "PaperStamp";

    private readonly ShaderInstance? _stampShader;

    // WL-Changes-start
    private readonly SpriteSystem _sprite;

    private StyleBoxTexture? _borderTexture;
    private TextureRect? _backgroundOverrideTexture;
    private StampLabel? _stampLabel;

    private float _orientation = 1.0f;
    public float Orientation
    {
        get
        {
            if (_stampLabel != null)
                return _stampLabel.Orientation;

            return _orientation;
        }
        set
        {
            if (_stampLabel != null)
                _stampLabel.Orientation = value;

            _orientation = value;
        }
    }

    public StampWidget()
    {
        RobustXamlLoader.Load(this);

        // WL-Changes-start
        _sprite = IoCManager.Resolve<IEntityManager>().System<SpriteSystem>();
        // WL-Changes-end

        var prototypes = IoCManager.Resolve<IPrototypeManager>();
        _stampShader = prototypes.Index(PaperStamp).InstanceUnique();
    }

    // WL-Changes-start
    public void UpdateVisuals(StampDisplayInfo stampInfo)
    {
        RemoveAllChildren();

        ModulateSelfOverride = null;
        PanelOverride = null;

        _borderTexture = null;
        _backgroundOverrideTexture = null;
        _stampLabel = null;

        var texture = _sprite.Frame0(stampInfo.StampedTexture);
        var textureScale = stampInfo.OverrideTextureSize ?? Vector2.One;

        if (stampInfo.StampedTextureIsBorder)
        {
            _stampLabel = new StampLabel()
            {
                Margin = new(12, 6),
                Text = Loc.GetString(stampInfo.StampedName),
                FontColorOverride = stampInfo.StampedColor
            };
            _stampLabel.StyleClasses.Add("LabelHeadingBigger");

            _borderTexture = new StyleBoxTexture()
            {
                Texture = texture,
                TextureScale = textureScale,
            };
            _borderTexture.SetPatchMargin(StyleBoxTexture.Margin.All, 7.0f);

            ModulateSelfOverride = stampInfo.StampedColor;
            PanelOverride = _borderTexture;

            AddChild(_stampLabel);
        }
        else
        {
            _backgroundOverrideTexture = new TextureRect
            {
                Texture = texture,
                TextureScale = textureScale,
                Stretch = TextureRect.StretchMode.Scale
            };

            AddChild(_backgroundOverrideTexture);
        }
    }
    // WL-Changes-end

    protected override void Draw(DrawingHandleScreen handle)
    {
        _stampShader?.SetParameter("objCoord", GlobalPosition * UIScale * new Vector2(1, -1));
        handle.UseShader(_stampShader);
        handle.SetTransform(GlobalPosition * UIScale, Orientation, Vector2.One);
        base.Draw(handle);

        // Restore a sane transform+shader
        handle.SetTransform(Matrix3x2.Identity);
        handle.UseShader(null);
    }
}
