using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._WL.UserInterface.Systems.Languages.Controls;

[GenerateTypedNameReferences]
public sealed partial class LanguagesControl : BoxContainer
{
    public LanguagesControl()
    {
        RobustXamlLoader.Load(this);
    }
}
